// <auto-generated />
using System;
using DocLocker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocLocker.API.Migrations
{
    [DbContext(typeof(DocLockerDbContext))]
    [Migration("20260529064242_AddChangeToUser")]
    partial class AddChangeToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocLocker.Core.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentRequestId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("bit");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("DocumentRequestId", "IsLatest");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DocLocker.Core.Models.DocumentRequest", b =>
                {
                    b.Property<int>("DocumentRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentRequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DocumentRequestStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("RequestedByManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DocumentRequestId");

                    b.HasIndex("DocumentRequestStatusId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RequestedByManagerId");

                    b.ToTable("DocumentRequests");
                });

            modelBuilder.Entity("DocLocker.Core.Models.DocumentRequestStatus", b =>
                {
                    b.Property<int>("DocumentRequestStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentRequestStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DocumentRequestStatusId");

                    b.ToTable("DocumentRequestStatuses");

                    b.HasData(
                        new
                        {
                            DocumentRequestStatusId = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            DocumentRequestStatusId = 2,
                            Name = "Submitted"
                        },
                        new
                        {
                            DocumentRequestStatusId = 3,
                            Name = "Approved"
                        },
                        new
                        {
                            DocumentRequestStatusId = 4,
                            Name = "Rejected"
                        },
                        new
                        {
                            DocumentRequestStatusId = 5,
                            Name = "RevisionRequested"
                        },
                        new
                        {
                            DocumentRequestStatusId = 6,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("DocLocker.Core.Models.DocumentRequestStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("DocumentRequestId");

                    b.HasIndex("StatusId");

                    b.ToTable("DocumentRequestStatusHistories");
                });

            modelBuilder.Entity("DocLocker.Core.Models.DocumentReview", b =>
                {
                    b.Property<int>("DocumentReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentReviewId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.HasKey("DocumentReviewId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ManagerId");

                    b.ToTable("DocumentReviews");
                });

            modelBuilder.Entity("DocLocker.Core.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByAdminId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProjectId");

                    b.HasIndex("CreatedByAdminId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DocLocker.Core.Models.ProjectManager", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId", "ManagerId");

                    b.HasIndex("ManagerId");

                    b.ToTable("ProjectManagers");
                });

            modelBuilder.Entity("DocLocker.Core.Models.ProjectMember", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("DocLocker.Core.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("DocLocker.Core.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("AllowUserManagement")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DocLocker.Core.Models.Document", b =>
                {
                    b.HasOne("DocLocker.Core.Models.DocumentRequest", "DocumentRequest")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocLocker.Core.Models.User", "UploadedByUser")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentRequest");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("DocLocker.Core.Models.DocumentRequest", b =>
                {
                    b.HasOne("DocLocker.Core.Models.DocumentRequestStatus", "Status")
                        .WithMany("Requests")
                        .HasForeignKey("DocumentRequestStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocLocker.Core.Models.User", "Member")
                        .WithMany("MemberDocumentRequests")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocLocker.Core.Models.Project", "Project")
                        .WithMany("DocumentRequests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocLocker.Core.Models.User", "RequestedByManager")
                        .WithMany("ManagerDocumentRequests")
                        .HasForeignKey("RequestedByManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Project");

                    b.Navigation("RequestedByManager");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DocLocker.Core.Models.DocumentRequestStatusHistory", b =>
                {
                    b.HasOne("DocLocker.Core.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocLocker.Core.Models.DocumentRequest", "DocumentRequest")
                        .WithMany("StatusHistory")
                        .HasForeignKey("DocumentRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocLocker.Core.Models.DocumentRequestStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("DocumentRequest");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DocLocker.Core.Models.DocumentReview", b =>
                {
                    b.HasOne("DocLocker.Core.Models.Document", "Document")
                        .WithMany("Reviews")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocLocker.Core.Models.User", "Manager")
                        .WithMany("Reviews")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("DocLocker.Core.Models.Project", b =>
                {
                    b.HasOne("DocLocker.Core.Models.User", "CreatedByAdmin")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByAdmin");
                });

            modelBuilder.Entity("DocLocker.Core.Models.ProjectManager", b =>
                {
                    b.HasOne("DocLocker.Core.Models.User", "Manager")
                        .WithMany("ProjectManagers")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocLocker.Core.Models.Project", "Project")
                        .WithMany("Managers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DocLocker.Core.Models.ProjectMember", b =>
                {
                    b.HasOne("DocLocker.Core.Models.User", "Member")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocLocker.Core.Models.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DocLocker.Core.Models.User", b =>
                {
                    b.HasOne("DocLocker.Core.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DocLocker.Core.Models.Document", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DocLocker.Core.Models.DocumentRequest", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("DocLocker.Core.Models.DocumentRequestStatus", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("DocLocker.Core.Models.Project", b =>
                {
                    b.Navigation("DocumentRequests");

                    b.Navigation("Managers");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("DocLocker.Core.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DocLocker.Core.Models.User", b =>
                {
                    b.Navigation("CreatedProjects");

                    b.Navigation("ManagerDocumentRequests");

                    b.Navigation("MemberDocumentRequests");

                    b.Navigation("ProjectManagers");

                    b.Navigation("ProjectMembers");

                    b.Navigation("Reviews");

                    b.Navigation("UploadedDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
